### ISSUE TITLE
Suggestion: rearrange the order of arguments in sample()

### ISSUE THREAD

**Issue by axefrog** [mostjs/core#135]
The current implementation of `sample()` is:

```ts
function sample<A, B, C>(f: (a: A, b: B) => C, sampler: Stream<A>, s: Stream<B>): Stream<C>;
```

I'd like to suggest that `b` should be the first argument of `f`, which would allow simpler composition in common scenarios, seeing as the point of sampling is generally to use the sampler as a signal to read the values on the main stream (`b`). By moving `b` to the first argument position, it'll allow the following, as an example:

```js
const clock = sample(identity, periodic(1000), Date.now);
// or
const firstName = sample(get('firstName'), sampler, person);
```

I can submit a PR if desired.

**Comment by briancavalier** [comment]
Hey @axefrog.  That's an interesting point about the intent of sample.  On one hand, I think it's worth considering making it easy, if this is common enough.

On the other hand, I feel like no matter what order we pick, someone will always want the other one.  That's mostly why `flip` exists in many languages.  It's also trivial to write your own one-liner to get a 1-arg version of sample:

```js
const sampled = sample((_, b) => b)
```

If what you want is only the sampled value, and you want to ignore the sampler value, then there's no reason for `f`.  The `sampled` above + map() is sufficient:

```js
const sampledValues = sampled(sampler, values).map(f)
```

Funnily enough, this is exactly [sampleWith in cujojs/most](https://github.com/cujojs/most/blob/master/docs/api.md#samplewith).  We actually had the reverse problem there: initially, cujojs/most _only_ provided sampleWith, and we had requests for a version that lets you access both the sampler and sampled values.  Perhaps that just means that the two are equally useful.

Anyway, thoughts on providing that as part of most/core?

My current feeling is that it's so easy via partial application that we can wait to see how common it is in practice before providing it.

**Comment by TylorS** [comment]
I use both `sampleWith` and `sample` quite a lot.

**Comment by axefrog** [comment]
Brian, valid points and the curried aspect does mitigate the issue to some degree. My point was not the desire to disregard the sampler value, as I recall the issue you mentioned in cujojs/most, having experienced it myself. I mainly just wanted to emphasize that the point of sampling, generally, is to "sample" the value whenever a cue is given via the sampler. This emphasis is realised by making the sampled value the first argument, and the sampler event the second argument, allowing the sampler value to be used as needed, but disregarded when it is not. I could be assuming incorrectly that people want just the sampled value more often than they want both?

There is no reason for sampling if the sampled value is to be disregarded, so I would put it to you that, given that 100% of cases require the sampled value, but <100% of cases require the sampler event value as well, that the latter should be the second argument, rather than the first.

**Comment by Frikki** [comment]
I’d like to raise awareness to the motivation of ordering parameters in functional programming.

1. The object to work on should be the last parameter because you can compose a sequence of operations on the object.
2. The order of the parameters except the last is not so critical.
3. It is easily possible to fix parameters, which are at the beginning.

**The Rule of Thumb**
The more important the parameter, the more frequently it changes, the more it shall be moved to the end of the parameter list. If there is some recursion involved, probably the parameter, which you recurse on, is the one that should be in the last position.

If parameter `b` functionally depends on parameter `a`, then `b` should be before `a`.

See also this answer: https://stackoverflow.com/a/5863222/883303

**Comment by axefrog** [comment]
@Frikki Sure, I understand that. My suggestion is with respect to the signature of the function referred to by the `f` argument itself though, not the `sample` function - not sure if that was clear. Given that the `f` function does not benefit from the composition you're referring to, at least not to the extent that it can have any meaningful interplay with a partially-composed `sample` function, it seems that the order of arguments of the `f` function doesn't affect the level of expressiveness available to a developer making use of the `sample` function. It's always possible I've missed a downside to what I'm suggesting though. In my mind, the order of arguments of the inner function seems to be only an improvement if reversed.

**Comment by briancavalier** [comment]
Sorry for letting this sit for a while.

### Current parameter order

One of most/core's primary API philosophies is for single-purpose functions of fixed arity, it makes sense to extend that philosophy to functions it accepts as arguments.  It seems reasonable to say that users who want to sample a stream either want both values, or only the *sampled* value.  Wanting only the *sampler* value would be pointless--it's effectively equivalent to the sampler stream itself.

So, callers are either going to want to write a 2 parameter function or a 1 parameter function (intentionally using the word [parameter and not argument](https://stackoverflow.com/questions/156767/whats-the-difference-between-an-argument-and-a-parameter)).  One cannot write a function that sometimes declares 2 parameters and sometimes declares 1 parameter.

It's fairly clear to me that `sample` currently covers the 2 parameter case--the case where a user cares about both values.

With that in mind, the parameter order of the 2-parameter user function currently aligns with @Frikki's [comment](https://github.com/mostjs/core/issues/135#issuecomment-330807492): the more important sampled value is last.  The parameter order also matches the order of the two streams that are parameters to `sampleWith`.

### A missing operation?

There is currently no builtin operation for the 1 parameter case, but it's trivial for a caller to build it.  However, I've heard from both @Frikki and @TylorS that they find themselves using a function like cujojs/most's sampleWith just as often as most/core's sample.  One of the points of this issue seems to be that it would be nice to be able to ignore the sampler value in some use cases.

All of that indicates to me that there's a missing operation similar to cujojs/most's sampleWith.

### Proposal

So, I propose that we add:

```js
function sampleAt <A, B> (sampler: Stream<A>, values: Stream<B>): Stream<B>
```

I quite like the name `sampleAt` for several reasons, with "at" pointing to the fact that it will sample `values` *at* the times defined by `sampler`.  I'm open to other names, of course, including `sampleWith`.  However, we've used "with" in other contexts that accept a function, e.g. recoverWith and continueWith.  This may be an opportunity to be more rigorous with names.  Other libs have used `sampledBy` for the name of this operation.  I'm not crazy about it, though.

Then, the 1-parameter function version can easily be done by combining `sampleAt` with `map`:

```js
map(f, sampleAt(sampled, values))
```

**Comment by axefrog** [comment]
Hey Brian, thanks for the reply. I'd be curious as to your thoughts on my reply to what Frikki said. What he said is absolutely valid, but as to what I'm suggesting, they seem immaterial, seeing as the function passed to `sample` does not benefit from currying or composition in any way at all, which is the whole point of putting the important argument last. It simply doesn't apply in this case, and in fact works _against_ function reuse, composition and currying, because you can't take existing functions that act on a (sampled) value and pass them as-is to `sample`, because sample is going to pass the sampler value first instead of the sampled value, which means you always need to pass `sample` a special function that has the sampler parameter first, whether or not you need it. Everything you were saying about needing the sampler value on its own is 100% correct. Because JavaScript does not enforce the declared set of paremeters upon the caller, it doesn't matter if the second parameter is omitted at the callsite:

```js
const multiply = curry2((n, m) => n * m);
const triple = multiply(3);
const counter = scan(n => n + 1, 0, skip(1, periodic(10)));

// Sample the counter once per second:
sample((a, b) => triple(b), periodic(1000), counter);

// ...but I don't need `a`. I'd prefer to do this:
sample(triple, periodic(1000), counter);

// Note that I'm not talking about reversing the parameter order of `sample`, but of `fn`.

// Rather than this:
function sample<A, B, C>(f: (a: A, b: B) => C, sampler: Stream<A>, s: Stream<B>): Stream<C>;

// This would be better:
function sample<A, B, C>(f: (b: B, a: A) => C, sampler: Stream<A>, s: Stream<B>): Stream<C>;
```

> My suggestion is with respect to the signature of the function referred to by the f argument itself though, not the sample function - not sure if that was clear. Given that the f function does not benefit from the composition you're referring to, at least not to the extent that it can have any meaningful interplay with a partially-composed sample function, it seems that the order of arguments of the f function doesn't affect the level of expressiveness available to a developer making use of the sample function. It's always possible I've missed a downside to what I'm suggesting though. In my mind, the order of arguments of the inner function seems to be only an improvement if reversed.

Could you show me a use case where the parameter order of the function passed to `sample` could benefit from having the sampler value first rather than last? I'm more than happy to stand corrected, it's just that nobody has come back with any arguments that seem to apply in this case, but rather only seem to be applicable to the more general ideas in functional programming, even though I can't see their relevance in this specific case.

**Comment by axefrog** [comment]
> The parameter order also matches the order of the two streams that are parameters to sampleWith

This is the only thing I can see that seems defensible in this case, and would appear to be the enforcement of an invariant in most's design, which is fine.

**Comment by axefrog** [comment]
Ok, I've come up with an answer to my own question. It seems like it'd be the less common case, but might be confusing from a consistency standpoint if the arguments of the user function were reversed, and would violate Okasaki's conventions, as referenced by @Frikki ...

```js
import { get } from '@collectable/red-black-tree';

const key$ = getStreamOfKeys();
const tree$ = getStreamOfLatestVersionOfTree();
const value$ = sample(get, key$, tree$);
```
