### ISSUE TITLE
What are the minimum requirements to create producer Stream

### ISSUE THREAD

**Issue by skylize** [mostjs/core#158]
Based on discussions in [cujos/most Issue #449](https://github.com/cujojs/most/issues/499) it seems like there is some interest in improving documentation for the custom stream api.

This is the first of hopefully many issues I will open, where I will try to leverage my naivety to create good questions about how things work, thus hopefully generating nice content for better docs. I will try my best to focus on core issues first (although since I don't really know what I'm doing I might make some mistakes about what is core), hopefully leading to enough lego-blocks for someone to jump right into creating a fully custom stream type.

So, as shown in the title, here is question 1:

_What are the minimum required pieces to satisfy the definition of a Source?_

(Bonus question: What are the suggested minimum requirements to create a safe production-ready Source?)

**Comment by briancavalier** [comment]
Hi @skylize.  A Stream is a type which produces events to a Sink.  It's described [here](http://mostcore.readthedocs.io/en/latest/api.html#stream).  The minimum requirement is to implement the run method, as per the type signature.

The dual to a Sink in `@most/core` is a Stream.  A Sink receives and processes events, and a Stream produces them.  There are sources (intentionally lower-case "sources") of events, but a Source is not a first class programming construct.

Some simple examples of a Stream are [`at`](https://github.com/mostjs/core/blob/master/packages/core/src/source/at.js), which generates an event at a particular time, and [`scan`](https://github.com/mostjs/core/blob/master/packages/core/src/combinator/scan.js) which accumulates event values over time.

You'll notice that scan implements both a Sink and a Stream, because it is a transformation on another Stream.  That is, it receives events, and also produces new ones.  This is also described in the [Stream](http://mostcore.readthedocs.io/en/latest/api.html#stream) docs.

**Comment by skylize** [comment]
> There are sources (intentionally lower-case "sources") of events, but a Source is not a first class programming construct.

Oh, thanks for that correction. I wonder where I got the idea that a source was a construct, and how much of my confusion may have stemmed from this mistake. I changed the title to reflect this.

So when I see `source` in the codebase, should I assume that to mean an upstream Stream?

> Some simple examples of a Stream are at, which generates an event at a particular time, and scan which accumulates event values over time.

Ahh. I like simple examples. :blush: 

One thing that stands out to me quickly is that the `run` method in `at` is returning a delay stream (am I using the correct terminology here?), while `scan` returns an instance of `DisposeAll`. How do these seemingly very different return types get resolved properly to observers?

**Comment by briancavalier** [comment]
> So when I see source in the codebase, should I assume that to mean an upstream Stream?

It's a fairly safe assumption, though I can't say it'll be true 100% of the time.  Becoming familiar with the [core set of types](http://mostcore.readthedocs.io/en/latest/api.html#most-types) hopefully will help.

> One thing that stands out to me quickly is that the run method in at is returning a delay stream

A [Stream's `run` method](http://mostcore.readthedocs.io/en/latest/api.html#stream) returns a [Disposable](http://mostcore.readthedocs.io/en/latest/api.html#disposable), which is, like Stream, an interface.

In particular, `at`'s `run` method schedules a delayed task to propagate an event at the desired time.  The [`delay` function is from `@most/scheduler`](https://github.com/mostjs/core/blob/master/packages/core/src/source/at.js#L4), docs [here](http://mostcore.readthedocs.io/en/latest/api.html#scheduler-delay).  Scheduling a task returns a [ScheduledTask](http://mostcore.readthedocs.io/en/latest/api.html#scheduledtask), which implements the Disposable interface.  Thus, the `run()` methods of `at` and `scan` are each returning a Disposable (though the concrete implementations happen to be different).

There's no need to do any further resolution: callers simply receive a Disposable in either case.

Hope that helps.

**Comment by briancavalier** [comment]
Hey @skylize, I'm going to close this.  I feel like the original and follow on questions have been answered, and the definition of a Stream is captured in its type definition in the documentation.
