### ISSUE TITLE
What is a sink?

### ISSUE THREAD

**Issue by skylize** [mostjs/core#159]
In our [quest to make custom streams available to all](https://github.com/mostjs/core/issues/158), let's go ahead and pound out a question 2:

_What is a Sink?_ 

I mean, I really feel like this word should be meaningful, but I can't seem to wrap my head around it. What even is this thing we call a Sink? And what is it's roll in a Stream?

**Comment by axefrog** [comment]
It's a computer science term which comes from electronics:

https://en.wikipedia.org/wiki/Current_sources_and_sinks

Loosely speaking, and with the caveat that there are exceptions to this in the strict sense, think of a stream as a "type" defining a source of data, and a sink as an "instance" of that type.

Here's how it works:

1. You run the stream and pass it a sink and a scheduler
2. If the stream needs to run any of its own sources (upstream streams):
  a. It constructs a sink of its own, wrapping your sink inside of the new sink it has created. In some cases it may not do this until later, if the stream has an asynchronous aspect to its behaviour. Sometimes it may reuse a sink, or the stream may double as a sink (multicast-like behaviour). In the latter case, your sink will probably be stored internally as part of the stream's state.
  b. It then runs its own upstream source (or sources, depending on the stream's implementation), passing the sink it owns, and the scheduler it received from your call to its run function, and the process then recurses through the stream graph until it hits one or more producers (streams with no upstream sources of their own).
3. The producer stream (or streams), activated through a call to its own `run` function, then uses the scheduler it has received to asynchronously begin emission of values back down through the stream graph, by calling `sink.event`. The `time` value that the sink's methods expect is generated by the scheduler. In some cases, the scheduler may be used to simply schedule the operation's start, at which point all values are then delivered to the sink synchronously. In other cases, it may schedule each event separately, using the scheduler in each case. For sources that are inherently asynchrous, such as mouse events, the scheduler is only used to retrieve the current `time` value, but otherwise no actual scheduling of events takes place, rather each event is just emitted directly to the sink by the producer, rather than via scheduler-controlled indirection.
4. The sink being emitted to will usually have enclosed within it an operation of some kind to perform on the value it receives via its `event` method. It performs that operation (it may something like a `map` method), and the result is then passed to the sink it has wrapped internally. That process then repeats until the value falls out the bottom of the stream graph, possibly into the garbage collector.

So what we really have here is a duality of two directed graphs, usually (but not always) acyclic in structure.

The first graph is the stream graph which represents an outbound covergence of all of the dataflow you've described while constructing it. Running the stream graph is like funnelling that intention down through the rest of the graph until the leaves of the graph (the producers) are eventually invoked.

The second graph is roughly the first graph's inverse, and acts like a set of funnels that flow downward from the producers, gradually converging back at the point from which `run` was originally called.

**Comment by skylize** [comment]
>  think of a stream as a "type" defining a source of data, and a sink as an "instance" of that type. ... You run the stream and pass it a sink and a scheduler

Umm. I think you lost me there. How can a sink be an instance of a stream if a stream must be given a sink? I'm sure it's just a problem of semantics, but from that description, there seems to be a chicken/egg problem.

According to the wiki article you linked "there is no intrinsic difference between a source and a sink". Does this statement hold true for `most`?

**Comment by briancavalier** [comment]
Thank you for that amazing and detailed reply, @axefrog!

@skylize Basically, a Sink is a type that receives and processes events, described [here](http://mostcore.readthedocs.io/en/latest/api.html#sink).

**Comment by Frikki** [comment]
A couple of year's ago, I wrote this on _sources_ and _sinks_:

> ... everything is a stream of events. On the client side, this can be user mouse clicks, mouse moves, key presses, touches, swipes, etc. On the server side, it can be stock ticks, Web page updates, order fulfillments, etc. Seen from a program’s perspective, these streams of events are from _sources_ in the outside world. It is the responsibility of the program to connect these observable streams and transform the data. To do this, the program must model the flow of data from these sources and build a sink, i.e., the output that is provided to the outside world ...

~ https://medium.com/@fkrautwald/plug-and-play-all-your-observable-streams-with-cycle-js-e543fc287872

**Comment by skylize** [comment]
> Thank you for that amazing and detailed reply, @axefrog!

Haha. Apologies for not myself offering a thank you here. This reply is quite detailed, and probably took a lot of thought to construct, even if it left me still a bit confused.

> a Sink is a type that receives and processes events, described here.

Unfortunately as a streams noob, I found the description there completely opaque. That's the reason I asked the question here, to hopefully get everyone brainstorming on a better way to describe it, that can hopefully be added to the docs for everyone.

**Comment by skylize** [comment]
> A couple of year's ago, I wrote this on sources and sinks:

Looks like an excellent article. 👍 Most of it I've only scanned over so far, but I will read it in detail several times over later on.

So one thing I thought was starting to click for me after that read is an idea that a sink would be the output path of a stream in comparison to the source being the input. But that becomes fuzzy again when I read something like this from the API docs: "A Sink receives events ... does something with them ... and then propagates them to another Sink." So here there seems to be no distinction between in and out, both cases are a sink. ???

**Comment by axefrog** [comment]
I think the important parts of my message got lost in that bad analogy. Ignore the sentence with that analogy in it and focus on the rest :-)

**Comment by skylize** [comment]
>  Ignore the sentence with that analogy in it and focus on the rest :-)

Ok. 😉 

You came up with a _great_ succinct description of the overall architecture of streaming with `most` and I think the docs could definitely use some intro text similar to that post.

That combined with some example code sampled directly from the core codebase next to each of the type descriptions would go a _long_ way toward helping new adopters find their footing.

Could I convince you to run through that process one more time with a simple example that doesn't worry about the graph and the what-ifs? Let's say I create a simple `of('some value')` and then observe it. How does that single value propagate through the `most` stack?

**Comment by axefrog** [comment]
With just an `of` stream, i.e. one producer stream, no combinators, and ultimately not doing anything much other than invoking the stream so that it does its thing and then ends.

![image](https://user-images.githubusercontent.com/298883/31802089-8eeaee14-b58f-11e7-8d24-59dbe265b6a4.png)

**Comment by skylize** [comment]
@axefrog Very nice. 👏 I think it's starting to make sense to me.

So in this diagram, would it be correct to say that if external consumer using `of` from `cujo/most` calls `myOfOneStream.observe(onEmit)`, this invokes `runEffects`, and on completion `SinkA.emit` would call `onEmit`  with the value `1`?

**Comment by axefrog** [comment]
Correct. In @<span/>most/core, there is no `observe()` function, you just call `runEffects()` yourself, and your `onEmit` function would maybe go into a `tap()` combinator:

```js
function onEmit(x) {
  // do stuff here
}
const stream = tap(onEmit, myOfOneStream);
const promise = runEffects(stream, newDefaultScheduler());
promise.catch(handleError);
```

**Comment by skylize** [comment]
> Correct for cujojs/most. In @most/core, though, there is no observe() function, you just call runEffects() yourself, and your onEmit function would maybe go into a tap() combinator:

Haha. Yes. I actually _did_ already catch that core does not have a built-in `observe`. Luckily I had an example shared by @TylorS of his new 6.0 version of `most-subject` that demonstrated a 1 liner `observe` function (not including imports) that has allowed me to at least dabble in trying to work with core directly.

`const observe = (f, stream) => drain(tap(f, stream))`

Actually, there doesn't seem to be an `of` or a `just` in core. So I guess using `of` implies using `cujos/must`.

**Comment by axefrog** [comment]
> Actually, there doesn't seem to be an of or a just in core. So I guess using of implies using cujos/must

You want the `now()` function.

**Comment by skylize** [comment]
> ```javascript
> function onEmit(x) { /* do stuff here */ }
> const stream = tap(onEmit, myOfOneStream);
> const promise = runEffects(stream, newDefaultScheduler());
> promise.catch(handleError);
> ```

Actually your example here is quite helpful here how `tap` actually connects with `cujos/most`'. I'm seeing more clearly how `tap` connects with `observe` method provided by `cujos/most`.

> You want the now() function.

Oh thanks. I was considering whether `of` / `just` should be a new question for me to post later. I was looking at `now` a few minutes ago. That makes sense.

**Comment by briancavalier** [comment]
Great discussion here.  Closing, as I feel like the takeaway is to add documentation for contributors and custom stream authors.  Those docs need to provide a different level of detail than the current API-level documentation.  I've added an item to the [1.x Backlog](https://github.com/mostjs/core/projects/4?) for that.
