### ISSUE TITLE
I miss operators from, fromEvent and create

### ISSUE THREAD

**Issue by mspoulsen** [mostjs/core#241]
In the old most.js we had operators from, fromEvent and create:
https://github.com/cujojs/most/blob/master/docs/api.md

Any reason why these have been left out of most/core?

Thnx!

**Comment by davidchase** [comment]
hi @mspoulsen thanks for the questions, i will try to answer them for you

`from` is not included simply because it does have really have a specific notion of time (events are a time + value pair) only order so we as a team decided to not include operators like such.
You can use `withItems` or `zipItems` which pair arrays with some provider of time like an another stream.

`fromEvent` is here https://github.com/mostjs/dom-event as renamed `domEvent` along with provided shortcuts to events like `click`, `mouseover`, etc
It was not included in the core simply because it is better suited as separate package allowing for the core to slim and focus on primitive operators

`create` has long been moved to https://github.com/mostjs/create, IMO it doesnt belong in the core because its an escape hatch for when a user can for some reason not use the declarative API.
Personally i think its better suited to create your own operator via Source/Sink pattern before importing the package `create`

hopefully this sheds some light for you, if you have more questions please dont hesitate to ask

i will cc the core team as they may have some other insights for you as well

cc/ @briancavalier @TylorS @Frikki

**Comment by mspoulsen** [comment]
Hi David,

Thank you very much for the prompt and in-depth reply.

I don't think @most/create is compatible with @most/core since it is still using the old Stream type, but I will look into the Source/Sink pattern you mentioned.

Thanks again!

**Comment by davidchase** [comment]
hi @mspoulsen im guessing you are referring to `create`? if you can describe what you are trying to achieve.. im sure we can come up with a nice solution.

> but I will look into the Source/Sink pattern you mentioned.

Dont need to look far its everywhere 😉  but a simple version is below:
https://github.com/mostjs/core/blob/51dd907474b8e0b0be16ee6846732a2f30ce55d9/packages/core/src/combinator/transform.js#L33-L58

and some good documentation to go along with it http://mostcore.readthedocs.io/en/latest/api.html#stream

**Comment by mspoulsen** [comment]
Yes, I meant `create`  :smirk:

Well, I am in the process of upgrading a semi-large codebase from cujojs/most to mostjs/core since that is what the latest version of motorcycle-ts uses (and I need to upgrade that in order to run the latest version of typescript).

Anyway, I am using `create` whenever I want to transform a third-party library (that uses callbacks for instance) to streams. I know most other streaming libraries have a similar operator and they are nice to have when integrating libraries.

Here is an example:

```javascript
export function tween(tweenProps: TweenProps): Stream<number> {
  return create(
    (add) => {
      _tween(tweenProps).start((n: number) => add(n))
    }
  )
}
```
popmotion is an animation library and delivers data via callbacks but since I would like to use only most.js in my codebase I adapt it to most like above. This works fine with cujojs/most.

How would I go about doing this with most/core?

**Comment by davidchase** [comment]
> How would I go about doing this with most/core?

Haven't tested this out but something along these lines:

```js
import { currentTime } from '@most/scheduler'

export function tween(tweenProps: TweenProps): Stream<number> {
  return new Tween(tweenProps)
}

class Tween {
  constructor(props) {
   this.tweenProps =  props
  }
  run(sink, scheduler) {
    const send = n => tryEvent(currentTime(scheduler), n, sink)

	_tween(this.tweenProps).start(send)
    // clean up
	return {dispose: () => {}}
  }
}

function tryEvent (t, x, sink) {
  try {
    sink.event(t, x)
  } catch (e) {
    sink.error(t, e)
  }
}
```

**Comment by mspoulsen** [comment]
Thanks, I really appreciate you helping me out!

However, as a consumer I find it puzzling that you do not include a function for this (like all other stream libraries). Almost all async libraries use either callbacks or Promises and creating adapters is such a common thing.

What is the reasoning behind not having a `create` function (anymore)?

**Comment by Frikki** [comment]
Hi @mspoulsen,

As @davidchase already mentioned, `create` is an imperative “escape hatch,” which doesn’t suit the core functionality of a declarative and reactive stream library. We have seen how people often and prematurely jump to use `create` instead of thinking about an external source of events that would be better suited for the stream. What I mean is that an “imperative” thought process often overshadows the use case.

If it is _really_ needed for you to handle the `popmotion` data as a time-value pair, then I would consider using `withItems` or `zipItems` with a stream that hold events for timing the emissions, e.g., `now` or `at` (or some other stream that you may already have available.) Another way could be to create a `Promise` and then use `fromPromise`.

**Comment by davidchase** [comment]
>  Almost all async libraries use either callbacks or Promises and creating adapters is such a common thing.

We have `fromPromise` so you can convert your callbacks into promise and then into streams 😛 or like the pattern mentioned above you can create a more general approach an create a `fromCb` operator

If you search `create` or `most.create` in the cujojs/most repo you will see there are a quite few issues surrounding it, that if you are not careful using it become a foot gun.

**Comment by mspoulsen** [comment]
Ahhh....`fromPromise`...there we go! I was looking for that one. I guess I missed it in the docs (yes, I did read it) because it was not located in the construction section. That's all I need. Thanks a lot!

...and hello Frederik! Long time no see! Good to see you are still going strong! :smirk:

**Comment by Frikki** [comment]
Thanks, Morten. You, too. Here, from @briancavalier, is a bit more info on `most/create`, i.e., why was removed from `cujojs/most` and why it isn’t part of the `@most/core`.

**Comment by davidchase** [comment]
> because it was not located in the construction section

Will add it to that section as well thanks @mspoulsen for the input its a valid point

**Comment by mspoulsen** [comment]
I don't wish to have or need `create` at all. I just needed some kind of adapter mechanism and `fromPromise` will do just fine (I just couldn't find it) :thumbsup:

Thanks again!

**Comment by davidchase** [comment]
sweet! be on the look out for the doc updates for `fromPromise` in the construction section of the API docs http://mostcore.readthedocs.io/en/latest/api.html#construction

**Comment by mspoulsen** [comment]
Can we re-open this?

The reason is that a Promise only returns **one** value. So I cannot use `fromPromise` when the callback delivers multiple values over time. This comes up a lot. In this case it is popmotion delivering numbers over time, but it could also be a socket.io connection delivering messages over time.

How would I adapt these values over time to a Stream if I don't have a `create` function ?

With `create` it becomes very simple:

```javascript
export function tween(tweenProps: TweenProps): Stream<number> {
  return create(
    (add) => {
      _tween(tweenProps).start((n: number) => add(n))
    }
  )
}
```
How about upgrading the separate `@most/create` package to a 3.0.0 that is compatible with `@most/core` 1.3.0? Atm they are not, because `Stream` is not the same type in both libraries. Would that be a solution? :slightly_smiling_face:
