### ISSUE TITLE
What is the lifecycle of a disposable returned from run?

### ISSUE THREAD

**Issue by skylize** [mostjs/core#264]
What object is in charge of deciding when/if a disposable returned from `.run` should be called? It seems like with combinators, disposables are getting propagated. But where do they ultimately land? When are they disposed of? Can that disposable be passed off to a 3rd party to use for canceling an active stream? Does/can/should the `.run` disposable have any specific relationship with a sink's `end` event?

**Comment by briancavalier** [comment]
Hey @skylize.

These are really good questions, thanks for asking.

First, the tl;dr:

> What object is in charge of deciding when/if a disposable returned from .run should be called?

* [`runEffects`](https://mostcore.readthedocs.io/en/latest/api.html#runeffects) manages this automatically, invoking the disposable when the end event occurs.  Intentionally, a disposable is never exposed to the caller of `runEffects`.
* [`run`](https://mostcore.readthedocs.io/en/latest/api.html#run) forces all responsibility for invoking the returned disposable onto the caller.

Before we dig it, a bit of context and philosophy.  A goal of most/core's API is for you to be able to express interest and disinterest in events declaratively using combinators like `since` and `until`, and not to have to try to manage disposables imperative yourself later, which can be tricky to get right (lots of asynchrony, potential for race conditions, etc.).  It's good to keep in mind that disposables often represent (scarce/limited) resources, such as socket connections, and not freeing them can result in resource leaks.

Of course, in the messy world of JS, there are bound to be situations where that isn't sufficient, and you need a finer degree of control (coupled with a higher degree of caution).

Ok, with that in mind, I'll do my best to answer the other questions.

> It seems like with combinators, disposables are getting propagated

Yes, exactly.  Specifically, as `run`'s type indicates, disposables are "propagated" in that they are transformed and combined as return values from `Stream` `run`.  Let's take a simple example of [`merge`](https://mostcore.readthedocs.io/en/latest/api.html#merge), which accepts 2 streams, and produces a new, merged stream.  The new, merged stream's `run` method will return a disposable which is the composition of the 2 disposables returned by the 2 streams being merged.

The [`@most/disposable`](https://mostcore.readthedocs.io/en/latest/api.html#most-disposable) package contains functions for transforming and combining disposables.

> But where do they ultimately land?

most/core has 2 functions for running a stream: `run` and `runEffects`:

* `run` is a trivial function wrapper around `Stream#run`, and simply returns the disposable to its caller, who assumes all responsibility for calling it.
* `runEffects` intentionally hides the disposable, and instead returns a promise to allow observing uncaught errors or the time at which the stream ends.  If you look at the implementation of runEffects, it basically just calls `Stream#run`, which returns the disposable, and then does some extra work to wrap it all up in a promise.

So, in the specific case of `run`, when should one invoke the disposable?

If you're implementing an application using `@most/core`.  You should arrange to invoke the disposable:

1. when the end event occurs on the associated stream, and
2. whenever else you need to based on your application use cases.

If you are implementing your own custom `@most/core` combinator:

1. _only_ in cases where your combinator needs to introduce specific behavior related to disposal, such as early disposal (like `take`).  Otherwise, the combinator should just transform, compose, and return disposables as required by the contract of `@most/core` types.  Looking at how other combinators are implemented can help.

> When are they disposed of?
> Does/can/should the .run disposable have any specific relationship with a sink's end event?

These two questions are closely related, as I'm betting you suspected.  The high level context is:

* End is a signal from producer to consumer indicating the producer will not produce any more events.  The owner of its disposable should now invoke the disposable.
* Disposal is a signal from consumer to producer indicating the consumer does not wish to consume any more events. The producer should not produce any more events, end or otherwise.

And a bit more detail:

* A stream will not (and in fact, _must not_) produce any events, end or otherwise, after a stream's disposable is invoked.  Specifically, Invoking a disposable will not cause an end event.  The intent is that disposal is forceful and immediate.
* `runEffects` arranges for a stream's disposable to be invoked automatically upon its end event.
* `run` _does not_ arrange for a stream's disposable to be invoked upon its end event.  The caller assumes all responsibility.  In this case, the caller should arrange for the disposable to be invoked upon receiving the end event.  Disposables are intended to be idempotent, which helps with race conditions.  Of course, there's no way `most/core` can guarantee that all disposables found in the wild (e.g. from other libraries) are actually idempotent.  `@most/disposable` provides [`disposeOnce`](https://github.com/mostjs/core/blob/master/packages/disposable/src/disposeOnce.js) to help with idempotency.

I hope all of that is helpful and informative!  It seems like you may have had a use case in mind when asking these questions.  If that's the case, let us know what it is, and we'll be able to offer more specific info.

**Comment by skylize** [comment]
Thanks @briancavalier. Great response.

I'll just leave the issue open a little longer in case someone will want to add further thoughts.

**Comment by skylize** [comment]
> @briancavalier
>
> Disposal is a signal from consumer to producer indicating the consumer does not wish to consume any more events. The producer should not produce any more events, end or otherwise.

What if streams `A` and `B` are both derived from the same source stream `S` wrapped around a disposable resource, and then `A` is disposed? 

Wouldn't that effectively end `B `by destroying its data producer, but with no signal of completion?

**Comment by briancavalier** [comment]
Another good question.  One thing to remember is that a Stream is inert and immutable.  It literally does nothing until you call `run`.  Thus, disposables are 1-1 with calls to run, i.e. with stream "activations", and not with the stream object.

With that in mind, there are 2 cases to consider in the scenario you described:

1. S is not multicast
2. S is multicast

### S is not multicast

In this scenario, there are 2 activations of S (that is, 2 calls to S's `run`): one for A, and one for B.  Thus, A and B each get their own, independent S disposable.  Does this mean any effects in S are executed twice?  Yes.  This is the standard model for "cold by default" streams, such as most and RxJS.  For non-effectful streams, or for streams whose underlying effects already handle multiple consumers (dom events, event emitters, EventTarget, and many others), this is just fine.

There are certainly cases where it's not just fine, and you don't want 2 activations of S, in which case you should multicast S.

### S is multicast

The multicast combinator effectively arranges for S to be reference counted.  Conceptually, each activation of S increases the reference count, and returns a disposable that decreases the reference count.  When the count changes from 0 to 1, the underlying stream (the one originally passed to multicast()) will be activated.  When the count again drops to 0, the underlying stream (the one passed to multicast()) will be disposed.

Thus, in the S A B scenario, a single activation of the stream underlying S is shared via reference counting between activations of A and B.  That activation (and any resources it allocated) will be disposed only after the activations of A and B have been disposed.

Hope that helps!

**Comment by skylize** [comment]
Helps a lot. Thanks
