### ISSUE TITLE
Inside a web worker

### ISSUE THREAD

**Issue by tryhardest** [mostjs/core#343]
Anyone try to use this in combination with a web worker thread and maybe a library like comlink?

**Comment by frank-dspeed** [comment]
i use it in webworkers its total no problem as it does not depend on any none js features.

**Comment by briancavalier** [comment]
@tryhardest Thanks for asking, and thank you, @frank-dspeed for sharing your experience.

As @frank-dspeed says, most has no specific dependencies that should cause a problem in a web worker.  It really only depends on setTimeout and promises, so everything should be fine.

I'll close this, since there's no issue to be fixed.  Please do feel free to continue to discuss, or report a problem if you encounter one.

Cheers!
